#pragma once

// AUTOGENERATED
// /home/duser/mk6/stack/apps/exampleETSI/src/RAW.asn1
//     to
// /home/duser/mk6/stack/apps/exampleETSI/src/raw-asn*

#ifdef __cplusplus
extern "C"
{
#endif
// with prefix 'RAW_'

// #define RAW_SomeData_??? ???

// RAW_ItsPduHeaderMessageID_ID
#define RAW_ItsPduHeaderMessageID_ID_denm                  1
#define RAW_ItsPduHeaderMessageID_ID_cam                   2
#define RAW_ItsPduHeaderMessageID_ID_poi                   3
#define RAW_ItsPduHeaderMessageID_ID_spatem                4
#define RAW_ItsPduHeaderMessageID_ID_mapem                 5
#define RAW_ItsPduHeaderMessageID_ID_ivim                  6
#define RAW_ItsPduHeaderMessageID_ID_ev_rsr                7
#define RAW_ItsPduHeaderMessageID_ID_tistpgtransaction     8
#define RAW_ItsPduHeaderMessageID_ID_srem                  9
#define RAW_ItsPduHeaderMessageID_ID_ssem                  10
#define RAW_ItsPduHeaderMessageID_ID_evcsn                 11
#define RAW_ItsPduHeaderMessageID_ID_dummy                 99

// RAW_ItsPduHeaderMessageID_Limit
#define RAW_ItsPduHeaderMessageID_Limit_Min                0
#define RAW_ItsPduHeaderMessageID_Limit_Max                255

// RAW_ItsPduHeaderProtocolVersion_ID
#define RAW_ItsPduHeaderProtocolVersion_ID_currentVersion  1

// RAW_ItsPduHeaderProtocolVersion_Limit
#define RAW_ItsPduHeaderProtocolVersion_Limit_Min          0
#define RAW_ItsPduHeaderProtocolVersion_Limit_Max          255

// RAW_SequenceNumber_Limit
#define RAW_SequenceNumber_Limit_Min                       0
#define RAW_SequenceNumber_Limit_Max                       65535

// RAW_StationID_Limit
#define RAW_StationID_Limit_Min                            0
#define RAW_StationID_Limit_Max                            4294967295

#ifdef __cplusplus
}
#endif
